server:
  port: 1234
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/hr
      username: root
      password: pass@word1
  h2:    console:      enabled: true
  jpa:    show-sql: true
    hibernate:      ddl-auto: update
      